# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-22 10:36
from __future__ import unicode_literals

from django.db import migrations, models
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_photo', pyuploadcare.dj.models.ImageField()),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.TextField(blank=True, max_length=140, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
