# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-23 09:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('neighbor', '0002_auto_20181023_0845'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='neighbourhood',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='neigh', to='neighbor.Neighbourhood'),
            preserve_default=False,
        ),
    ]
